# Generated by Django 4.1.3 on 2022-12-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contact_chat_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='friends',
        ),
    ]
