# Generated by Django 4.1.3 on 2022-12-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_contact_username_remove_contact_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='user',
        ),
    ]
