# Generated by Django 4.1.3 on 2022-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_contact_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='inactive', max_length=255),
        ),
    ]
